[package]
name = "market-badger"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = { version = "0.12.4", features = ["cache"] }
tokio = { version = "1.44.0", features = ["rt-multi-thread"] }
